### ISSUE TITLE
Add Support For NSA Suite B Cryptography Algorithms

### ISSUE THREAD

**Issue by war59312** [rssowl/RSSOwl#12]
Hi,

Please Add Support For NSA Suite B Cryptography Algorithms.

Without this support, secure feeds that use these algorithms will fail to load in RSSOwl.

With the error: "could not generate dh keypair"

Example Feed: https://www.reactos.org/blog/feed

See Bug Fix @ http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7044060

See https://github.com/rssowl/RSSOwl/issues/11

Thanks,

Will

PS: Related forum thread: https://sourceforge.net/p/rssowl/discussion/296910/thread/5df8a310/?limit=25#ac63

**Comment by genodeftest** [comment]
The "Bug Fix" page says that this issue is fixed in Java 8u56 and later. Which version of Java are you running? Can you please try again with the latest Java 8 (Java 8u131 at the time of writing this comment)?

**Comment by genodeftest** [comment]
Since updating Java is not RSSOwl's task, I'll close this bug. Please update your system Java installation (and keep auto-update enabled).

**Comment by war59312** [comment]
Think you misunderstand. That's OK.

I pointed to the JDK (Java Development Kit) bug fix so you could see that it's fixed in the development kit.

It's nothing to do with the user's installed version of java, as in the Java Runtime.

RSSOwl needs to be rebuilt using a newer version of the JDK to fix this issue.

**Comment by JLChamberlain** [comment]
Who will rebuild it?, no one is maintaining RSSOwl?, I also cant get certain feeds to work with RSSOwl!

**Comment by Neustradamus** [comment]
I would like too new builds of RSSOwl with https support :)

**Comment by war59312** [comment]
How to build @ https://github.com/bpasero/rssowl-target

Perhaps one of these days I'll get bored and irritated enough to build it and update it.

For now I just use this to regenerate working RSS link: http://albirew.fr/bordel/coto_rss.php
