### ISSUE TITLE
Santa Claus came early this year. (RSSOwl update)

### ISSUE THREAD

**Issue by Xyrio** [rssowl/RSSOwl#19]
;)

but it is a pre relase/beta.

https://github.com/Xyrio/RSSOwl
https://github.com/Xyrio/RSSOwl/releases

**Comment by genodeftest** [comment]
That looks very promising. Are you interested in merging the changes to the RSSOwl repository?

**Comment by Xyrio** [comment]
created a pull request. do as u like.

**Comment by genodeftest** [comment]
See #20.
